left_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05

right_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05

# left_arm:
#   kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
#   kinematics_solver_timeout: 0.05
#   solve_type: Speed  # 可选 Speed/Distance/Manipulation1/Manipulation2
#   position_only_ik: false
#   kinematics_solver_search_resolution: 0.005
#   ik_link: left_ee_link  # 指定末端执行器链路名称

# right_arm:
#   kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
#   kinematics_solver_timeout: 0.05
#   solve_type: Speed
#   position_only_ik: false
#   kinematics_solver_search_resolution: 0.005
#   ik_link: right_ee_link