controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ur_arm_left_ros2_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    ur_arm_right_ros2_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    inspire_hand_left_ros2_controller:
      type: forward_command_controller/ForwardCommandController
    inspire_hand_right_ros2_controller:
      type: forward_command_controller/ForwardCommandController

ur_arm_left_ros2_controller:
  ros__parameters:
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

ur_arm_right_ros2_controller:
  ros__parameters:
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

inspire_hand_left_ros2_controller:
  ros__parameters:
    joints:
      - left_hand_L_thumb_proximal_yaw_joint
      - left_hand_L_thumb_proximal_pitch_joint
      - left_hand_L_index_proximal_joint
      - left_hand_L_middle_proximal_joint
      - left_hand_L_ring_proximal_joint
      - left_hand_L_pinky_proximal_joint

    interface_name: position

inspire_hand_right_ros2_controller:
  ros__parameters:
    joints:
      - right_hand_R_thumb_proximal_yaw_joint
      - right_hand_R_thumb_proximal_pitch_joint
      - right_hand_R_index_proximal_joint
      - right_hand_R_middle_proximal_joint
      - right_hand_R_ring_proximal_joint
      - right_hand_R_pinky_proximal_joint

    interface_name: position
