publisher_inspire_hand_left:
  ros__parameters:
    wait_sec_between_publish: 5
    publish_topic: "/inspire_hand_left_ros2_controller/commands"

    goal_names: ["open", "close", "half_open", "thumb_only"]

    open: [
      1.3, 0.5, 1.7, 1.7, 1.7, 1.7  # 左手 6 个关节
    ]
    close: [
      -0.1, 0.0, 0.0, 0.0, 0.0, 0.0
    ]
    half_open: [
      0.6, 0.25, 0.85, 0.85, 0.85, 0.85
    ]
    thumb_only: [
      1.3, 0.5, 0.0, 0.0, 0.0, 0.0
    ]

publisher_inspire_hand_right:
  ros__parameters:
    wait_sec_between_publish: 5
    publish_topic: "/inspire_hand_right_ros2_controller/commands"

    goal_names: ["open", "close", "half_open", "thumb_only"]

    open: [
      1.3, 0.5, 1.7, 1.7, 1.7, 1.7  # 右手 6 个关节
    ]
    close: [
      -0.1, 0.0, 0.0, 0.0, 0.0, 0.0
    ]
    half_open: [
      0.6, 0.25, 0.85, 0.85, 0.85, 0.85
    ]
    thumb_only: [
      1.3, 0.5, 0.0, 0.0, 0.0, 0.0
    ]
