controller_manager:
  ros__parameters:
    update_rate: 30

    ur_arm_left_ros2_controller:
      type:  position_controllers/JointGroupPositionController
    ur_arm_right_ros2_controller:
      type: position_controllers/JointGroupPositionController

ur_arm_left_ros2_controller:
  ros__parameters:
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

ur_arm_right_ros2_controller:
  ros__parameters:
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

left_arm_node:
  ros__parameters:
    debugging: false
    show_tcp_data: false
    tcp_port: 45678
    chain_root: stand
    chain_tip: left_ee_link
    robot_arm_length: 0.917
    human_arm_length: 0.6
    z_init: 0.916
    Z_bias: 1.3

right_arm_node:
  ros__parameters:
    debugging: false
    show_tcp_data: false
    tcp_port: 34567
    chain_root: stand
    chain_tip: right_ee_link
    robot_arm_length: 0.917
    human_arm_length: 0.6
    z_init: 0.916
    Z_bias: 1.3

fingers_node:
  ros__parameters:
      show_tcp_data: false
      tcp_port: 23456

/**:
  ros__parameters:
    use_sim_time: true
    use_rviz: false