controller_manager:
  ros__parameters:
    update_rate: 30

    ur_arm_left_ros2_controller:
      type:  position_controllers/JointGroupPositionController
    ur_arm_right_ros2_controller:
      type: position_controllers/JointGroupPositionController

ur_arm_left_ros2_controller:
  ros__parameters:
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

ur_arm_right_ros2_controller:
  ros__parameters:
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity